version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:22 # Use an appropriate Node.js version

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install pnpm
          command: npm install -g pnpm

      - run:
          name: Install dependencies
          command: pnpm install

      - run:
          name: Build project
          command: pnpm build

workflows:
  version: 2
  build:
    jobs:
      - build
